# Generated by Django 4.1.2 on 2022-10-28 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('cedula', models.CharField(max_length=17)),
                ('correo', models.CharField(max_length=50)),
                ('celular', models.IntegerField()),
            ],
        ),
    ]
